# Dockerfile for Nginx
FROM nginx:latest

# Remove default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom configuration
COPY nginx.conf /etc/nginx/conf.d

# Expose HTTP and HTTPS ports
EXPOSE 80 443
