version: "3.7"

services:
  postgres-db-primary:
    image: postgres:14
    restart: unless-stopped
    ports:
    - "127.0.0.1:5432:5432"
    volumes:
      - ./pgdata/:/var/lib/postgresql/data
      - ./postgres-confs/primary.conf:/etc/postgresql/postgresql.conf
      - ./db-init:/docker-entrypoint-initdb.d
      - ./postgres-confs/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./entrypoint.sh/:/opt/entrypoint.sh
    networks:
      coffee-pipeline:
    environment:
      - POSTGRES_PASSWORD=enter1234
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DATABASE_TYPE=primary
    command: ["bin/sh", "-c", "chmod +x /opt/entrypoint.sh; ./opt/entrypoint.sh"]

  postgres-db-replica:
    image: postgres:14
    restart: unless-stopped
    ports:
    - "127.0.0.1:5433:5432"
    volumes:
      - ./pgdata-replica/:/var/lib/postgresql/data
      - ./entrypoint.sh/:/opt/entrypoint.sh
      - ./pg_ping.sh/:/opt/pg_ping.sh
      - ./postgres-confs/replica.conf:/etc/postgresql/postgresql.conf
    networks:
      coffee-pipeline:
    environment:
      - POSTGRES_PASSWORD=enter1234
      - PGAPPNAME=replica_1
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DATABASE_TYPE=replica
    command: ["bin/sh", "-c", "chmod +x /opt/entrypoint.sh; ./opt/entrypoint.sh; "]

  # postgres-db-shard:
  #   image: postgres:14
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres-db-primary
  #   ports:
  #   - "127.0.0.1:5434:5432"
  #   volumes:
  #     - ./pgdata-shard/:/var/lib/postgresql/data
  #     - ./entrypoint.sh/:/opt/entrypoint.sh
  #     - ./postgres-confs/shard.conf:/etc/postgresql/postgresql.conf
  #   networks:
  #     coffee-pipeline:
  #   environment:
  #     - POSTGRES_PASSWORD=enter1234
  #     - PGAPPNAME=shard_1
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_HOST_AUTH_METHOD=trust
  #     - DATABASE_TYPE=shard
  #   command: ["bin/sh", "-c", "chmod +x /opt/entrypoint.sh; ./opt/entrypoint.sh"]

networks:
  coffee-pipeline:
    


